### ISSUE TITLE
BODY_21A not available and only one person tracking?

### ISSUE THREAD

**Issue by ryannfinn** [soulslicer/openpose#17]
I've already run the .sh file, but when I run the command `build/examples/openpose/openpose.bin --model_pose BODY_21A --tracking 1 --render_pose 1`, the error message `String (`BODY_21A`) does not correspond to any model (BODY_25, COCO, MPI, MPI_4_layers)` appears. 

And if I deleted the `--model_pose BODY_21A` flag or run with `--model_pose BODY_25`, the following error message appears:

```Person tracking (`--tracking` flag) is in experimental phase and only allows tracking of up to 1 person at the time. Please, also include the `--number_people_max 1` flag when using the `--tracking` flag. Tracking more than one person at the time is not expected as short- nor medium-term goal.```

Is there anything I can do to run the demo with multi-person tracking? Or is it really that only single person tracking is available at the moment? 

Thanks!

**Comment by gineshidalgo99** [comment]
@soulslicer will know better, but I believe this repo does not need the tracking flag. Simply using model_pose BODY_21A should already give you the people tracking?

**Comment by soulslicer** [comment]
Hi Yes, you need to look at the STAF repo found on the STAF page
