### ISSUE TITLE
Running inference doesn't produce person_ID's when running STAF

### ISSUE THREAD

**Issue by BroderickHigby** [soulslicer/openpose#3]
### Issue Summary

*Ran inference using the example code, and no person_ID tracking happens*

### Executed Command (if any)
Note: add `--logging_level 0 --disable_multi_thread` to get higher debug information.

`./build/examples/openpose/openpose.bin --video examples/media/video.avi --write_video output/makeithot.avi --write_json output/ --model_pose BODY_25 --render_pose 2 --tracking 0

### OpenPose Output (if any)

```{"version":1.3,"people":[{"person_id":[],"pose_keypoints_2d":[762.894,341.857,0.9845,727.531,436.005,0.859083,647.967,433.189,0.808931,645.041,550.937,0.807426,756.881,598.082,0.847462,812.774,438.999,0.850725,871.685,562.654,0.453353,883.382,556.819,0.714393,789.368,633.314,0.639624,736.262,645.098,0.608079,859.943,695.053,0.878571,871.723,907.091,0.592937,851.103,621.622,0.639177,1068.91,668.458,0.872738,1118.97,904.126,0.713615,742.26,321.305,0.941923,774.594,327.235,0.834386,695.1,335.955,0.884205,0,0,0,1183.71,912.903,0.352292,1180.73,907.05,0.352431,1115.98,927.514,0.442241,907.035,927.523,0.117059,898.148,933.516,0.113883,862.88,924.612,0.341001],"face_keypoints_2d":[],"hand_left_keypoints_2d":[],"hand_right_keypoints_2d":[],"pose_keypoints_3d":[],"face_keypoints_3d":[],"hand_left_keypoints_3d":[],"hand_right_keypoints_3d":[]}]}```

### Errors (if any)

No errors, was not able to reproduce paper's results from running inference. When BODY_21A was passed, the error that it could not be found was produced.

### Type of Issue
You might select multiple topics, delete the rest:
- Help wanted
- Question
- Enhancement / offering possible extensions / pull request / etc
- Other (type your own type)
         *Was not able to replicate results in README.md* 

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: LINK

*running regular openpose through docker on GCP. There are no errors.*

2. **OpenPose version**: Latest GitHub code? Or specific commit (e.g., d52878f)? Or specific version from `Release` section (e.g., 1.2.0)?
`openpose/staf` latest version

3. **General configuration**:
    - **Installation mode**: CMake, sh script, manual Makefile installation, ... (Ubuntu); CMake, ... (Windows); ...?
    - **Operating system** (`lsb_release -a` in Ubuntu):
    - **Operating system version** (e.g., Ubuntu 16, Windows 10, ...):
    - **Release or Debug mode**? (by default: release):
    - Compiler (`gcc --version` in Ubuntu or VS version in Windows): 5.4.0, ... (Ubuntu); VS2015 Enterprise Update 3, VS2017 community, ... (Windows); ...?

ubuntu deep learning machine. CUDA 10.0. OP/master runs fine.

**Comment by soulslicer** [comment]
Hi, The only Model with tracking now is BODY_21A. I will be working on releasing a pytorch version of the training code this December that should let one training a BODY_25B model

**Comment by BroderickHigby** [comment]
in the file:`openpose/src/openpose/utilities/flagsToOpenPose.cpp`

` "pose/body_21a/pose_deploy.prototxt"` 

should say: 

`"pose/body_21a_video/pose_deploy.prototxt",`

**Comment by BroderickHigby** [comment]
Renaming `models/pose/body_21a_video` to `models/pose/body_21a` and changing the enclosed caffeModel from `pose_iter_264000.caffemodel` to `pose_iter_XXXXXX.caffemodel` fixed the BODY_21A not being found.  Running `./build/examples/openpose/openpose.bin --video makeithot.mp4 --write_video output/makeithot.avi --write_json output/  --render_pose 2 --tracking 0 --number_people_max 1 --model_pose BODY_21A --logging_level 0 --disable_multi_thread` caused an error with `concat_layer.cpp shapes being 46 vs. 82. This is defined in the `pose_deploy.prototxt` file. The full error is: 

./build/examples/openpose/openpose.bin --video makeithot.mp4 --write_video output/makeithot.avi --write_json output/  --render_pose 2 --tracking 0 --number_people_max 1 --model_pose BODY_21A --logging_level 0 --disable_multi_thread


```
(fb) (base) datahinge-lin-1@datahingeli1-MS-7A38:/media/datahinge-lin-1/New Volume/openpose$ ./build/examples/openpose/openpose.bin --video makeithot.mp4 --write_video output/makeithot.avi --write_json output/  --render_pose 2 --tracking 0 --number_people_max 1 --model_pose BODY_21A --logging_level 0 --disable_multi_thread
Starting OpenPose demo...
Configuring OpenPose...
/media/datahinge-lin-1/New Volume/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToProducer():198
/media/datahinge-lin-1/New Volume/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToProducerType():161
/media/datahinge-lin-1/New Volume/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToPoseMode():11
/media/datahinge-lin-1/New Volume/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToPoseModel():32
/media/datahinge-lin-1/New Volume/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToScaleMode():83
/media/datahinge-lin-1/New Volume/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToHeatMapScaleMode():112
/media/datahinge-lin-1/New Volume/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToDetector():138
/media/datahinge-lin-1/New Volume/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToDetector():138
Starting thread(s)...
/media/datahinge-lin-1/New Volume/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():102
/media/datahinge-lin-1/New Volume/openpose/src/openpose/producer/producer.cpp:createProducer():413
/media/datahinge-lin-1/New Volume/openpose/src/openpose/wrapper/wrapperAuxiliary.cpp:wrapperConfigureSanityChecks():17
/media/datahinge-lin-1/New Volume/openpose/src/openpose/wrapper/wrapperAuxiliary.cpp:wrapperConfigureSanityChecks():184
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
/media/datahinge-lin-1/New Volume/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():368
/media/datahinge-lin-1/New Volume/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():433
/media/datahinge-lin-1/New Volume/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():438
/media/datahinge-lin-1/New Volume/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():449
/media/datahinge-lin-1/New Volume/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():503
/media/datahinge-lin-1/New Volume/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():555
/media/datahinge-lin-1/New Volume/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():599
/media/datahinge-lin-1/New Volume/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():643
/media/datahinge-lin-1/New Volume/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():660
/media/datahinge-lin-1/New Volume/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():677
/media/datahinge-lin-1/New Volume/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():696
/media/datahinge-lin-1/New Volume/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():712
/media/datahinge-lin-1/New Volume/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():745
/media/datahinge-lin-1/New Volume/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():770
/media/datahinge-lin-1/New Volume/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():775
/media/datahinge-lin-1/New Volume/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():779
/media/datahinge-lin-1/New Volume/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():795
/media/datahinge-lin-1/New Volume/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():796
/media/datahinge-lin-1/New Volume/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():805
/media/datahinge-lin-1/New Volume/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():810
/media/datahinge-lin-1/New Volume/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():822
/media/datahinge-lin-1/New Volume/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():826
/media/datahinge-lin-1/New Volume/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():842
/media/datahinge-lin-1/New Volume/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():863
/media/datahinge-lin-1/New Volume/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():872
/media/datahinge-lin-1/New Volume/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():876
/media/datahinge-lin-1/New Volume/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():882
/media/datahinge-lin-1/New Volume/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():941
/media/datahinge-lin-1/New Volume/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():957
/media/datahinge-lin-1/New Volume/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():963
/media/datahinge-lin-1/New Volume/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():1039
/media/datahinge-lin-1/New Volume/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():1073
/media/datahinge-lin-1/New Volume/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():1177
/media/datahinge-lin-1/New Volume/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():1201
/media/datahinge-lin-1/New Volume/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():1208
/media/datahinge-lin-1/New Volume/openpose/include/openpose/wrapper/wrapper.hpp:exec():439
/media/datahinge-lin-1/New Volume/openpose/include/openpose/thread/threadManager.hpp:exec():185
/media/datahinge-lin-1/New Volume/openpose/include/openpose/thread/queueBase.hpp:addPusher():362
/media/datahinge-lin-1/New Volume/openpose/include/openpose/thread/queueBase.hpp:addPusher():362
/media/datahinge-lin-1/New Volume/openpose/include/openpose/thread/queueBase.hpp:addPusher():362
/media/datahinge-lin-1/New Volume/openpose/include/openpose/thread/threadManager.hpp:exec():190
/media/datahinge-lin-1/New Volume/openpose/include/openpose/thread/thread.hpp:threadFunction():182
/media/datahinge-lin-1/New Volume/openpose/include/openpose/thread/thread.hpp:initializationOnThread():167
Starting initialization on thread. In /media/datahinge-lin-1/New Volume/openpose/src/openpose/pose/poseExtractorCaffe.cpp:netInitializationOnThread():174
Finished initialization on thread. In /media/datahinge-lin-1/New Volume/openpose/src/openpose/pose/poseExtractorCaffe.cpp:netInitializationOnThread():193
Starting initialization on thread. In /media/datahinge-lin-1/New Volume/openpose/src/openpose/pose/poseGpuRenderer.cpp:initializationOnThread():74
Finished initialization on thread. In /media/datahinge-lin-1/New Volume/openpose/src/openpose/pose/poseGpuRenderer.cpp:initializationOnThread():84
/media/datahinge-lin-1/New Volume/openpose/include/openpose/thread/thread.hpp:threadFunction():185
/media/datahinge-lin-1/New Volume/openpose/include/openpose/producer/wDatumProducer.hpp:workProducer():64
/media/datahinge-lin-1/New Volume/openpose/include/openpose/producer/wDatumProducer.hpp:workProducer():81
/media/datahinge-lin-1/New Volume/openpose/include/openpose/thread/wIdGenerator.hpp:work():62
/media/datahinge-lin-1/New Volume/openpose/include/openpose/thread/wIdGenerator.hpp:work():78
/media/datahinge-lin-1/New Volume/openpose/include/openpose/core/wScaleAndSizeExtractor.hpp:work():62
/media/datahinge-lin-1/New Volume/openpose/include/openpose/core/wScaleAndSizeExtractor.hpp:work():76
/media/datahinge-lin-1/New Volume/openpose/include/openpose/core/wCvMatToOpInput.hpp:work():61
/media/datahinge-lin-1/New Volume/openpose/include/openpose/core/wCvMatToOpInput.hpp:work():72
/media/datahinge-lin-1/New Volume/openpose/include/openpose/core/wCvMatToOpOutput.hpp:work():62
/media/datahinge-lin-1/New Volume/openpose/include/openpose/core/wCvMatToOpOutput.hpp:work():75
/media/datahinge-lin-1/New Volume/openpose/include/openpose/pose/wPoseExtractor.hpp:work():69
F1109 19:23:45.067231 15575 concat_layer.cpp:42] Check failed: top_shape[j] == bottom[i]->shape(j) (46 vs. 82) All inputs must have the same shape, except at concat_axis.
*** Check failure stack trace: ***
    @     0x7f17011ce5cd  google::LogMessage::Fail()
    @     0x7f17011d0433  google::LogMessage::SendToLog()
    @     0x7f17011ce15b  google::LogMessage::Flush()
    @     0x7f17011d0e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f1700bbf7c1  caffe::ConcatLayer<>::Reshape()
    @     0x7f1700cbd29d  caffe::Net<>::Reshape()
    @     0x7f17027a6d1d  op::NetCaffe::forwardPass()
    @     0x7f17027c4d4a  op::PoseExtractorCaffe::forwardPass()
    @     0x7f17027bef95  op::PoseExtractor::forwardPass()
    @     0x7f17027bc0f0  op::WPoseExtractor<>::work()
    @     0x7f1702814889  op::Worker<>::checkAndWork()
    @     0x7f1702814a2b  op::SubThread<>::workTWorkers()
    @     0x7f170281d3cb  op::SubThreadQueueInOut<>::work()
    @     0x7f17028177db  op::Thread<>::threadFunction()
    @     0x7f1702817b80  op::Thread<>::exec()
    @     0x7f170281b2ad  op::ThreadManager<>::exec()
    @     0x7f1702872833  op::WrapperT<>::exec()
    @           0x408c31  openPoseDemo()
    @           0x4077f3  main
    @     0x7f1701a3b830  __libc_start_main
    @           0x407829  _start
    @              (nil)  (unknown)
Aborted (core dumped)
```

**Comment by soulslicer** [comment]
I am sorry but I have no idea what you are trying to do. Those codes shouldn't be modified. It only works with BODY_21A in tracking mode for now

**Comment by BroderickHigby** [comment]
Hey SoulSlicer,

When I try to run: 
`build/examples/openpose/openpose.bin --model_pose BODY_21A --tracking 1 --render_pose 1` 

or any semblance of the command, I receive the error:
`String ('BODY_21A') does not correspond to any model (BODY_25, COCO, MPI, MPI_4_layers).` 

 It seems that there may be a discrepancy in get models.sh that names the folder `models/pose/body_21a_video` when getting the model. The other references to the folder throughout the code use the folder name `models/pose/body_21a/`. However, simply changing the folder name still produces the same error.

**Comment by arcf2013** [comment]
Where can I download the BODY_21A?

**Comment by BroderickHigby** [comment]
You can download BODY_21A in the getmodels.sh file

**Comment by AtifSarwar29** [comment]
> You can download BODY_21A in the getmodels.sh file



> Hey SoulSlicer,
> 
> When I try to run:
> `build/examples/openpose/openpose.bin --model_pose BODY_21A --tracking 1 --render_pose 1`
> 
> or any semblance of the command, I receive the error:
> `String ('BODY_21A') does not correspond to any model (BODY_25, COCO, MPI, MPI_4_layers).`
> 
> It seems that there may be a discrepancy in get models.sh that names the folder `models/pose/body_21a_video` when getting the model. The other references to the folder throughout the code use the folder name `models/pose/body_21a/`. However, simply changing the folder name still produces the same error.

hi, @BroderickHigby have you solved this issue? I am running this command it shows me this: 

root@1c76792657a3:/openpose# ./build/examples/openpose/openpose.bin --model_pose BODY_21A --tracking 1 --render_pose 1 --video examples/media/video.avi --write_video /atif/nol22.avi --write_json /atif/poses --display 0
Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
RUNNING PoseExtractorCaffeStaf::PoseExtractorCaffeStaf
F0629 06:41:27.233839   322 pooling_layer.cu:212] Check failed: error == cudaSuccess (48 vs. 0)  no kernel image is available for execution on the device
*** Check failure stack trace: ***
    @     0x7fb677bea0cd  google::LogMessage::Fail()
    @     0x7fb677bebf33  google::LogMessage::SendToLog()
    @     0x7fb677be9c28  google::LogMessage::Flush()
    @     0x7fb677bec999  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fb6777be02b  caffe::PoolingLayer<>::Forward_gpu()
    @     0x7fb67770b032  caffe::Net<>::ForwardFromTo()
    @     0x7fb679645c87  op::NetCaffe::forwardPass()
    @     0x7fb67967747e  op::PoseExtractorCaffeStaf::forwardPass()
    @     0x7fb679667505  op::PoseExtractor::forwardPass()
    @     0x7fb6796642d1  op::WPoseExtractor<>::work()
    @     0x7fb6796c78d9  op::Worker<>::checkAndWork()
    @     0x7fb6796c7a63  op::SubThread<>::workTWorkers()
    @     0x7fb6796d16c8  op::SubThreadQueueInOut<>::work()
    @     0x7fb6796c9d41  op::Thread<>::threadFunction()
    @     0x7fb678b0066f  (unknown)
    @     0x7fb6782226db  start_thread
    @     0x7fb67855b88f  clone
Aborted (core dumped)

**Comment by BroderickHigby** [comment]
Hey @AtifSarwar29, this was a huge pain for me. If you go into the pose_tracking file and change body_25 to body_21 that should fix it. Also, make sure that the body_21 model is actually downloaded in your models/pose folder. Then rebuild the project using: 
cd build/; make -j `nproc`; cd ../

Check out my branch if you need to: 
https://github.com/BroderickHigby/openpose/tree/staf-ubuntu

Last ditch efforts, if you want, here’s my docker. You just run that up and you’ll have staf ready to go. 

docker pull broderickhigby/openpose-staf:latest


Medium article to set it up:
https://medium.com/@brodyhigby/how-to-get-openpose-with-spatial-temporal-fields-running-in-under-5-minutes-123e94aafe12


Wrote this on my phone.

**Comment by AtifSarwar29** [comment]
> Hey @AtifSarwar29, this was a huge pain for me. If you go into the pose_tracking file and change body_25 to body_21 that should fix it. Also, make sure that the body_21 model is actually downloaded in your models/pose folder. Then rebuild the project using:
> cd build/; make -j `nproc`; cd ../
> 
> Check out my branch if you need to:
> https://github.com/BroderickHigby/openpose/tree/staf-ubuntu
> 
> Last ditch efforts, if you want, here’s my docker. You just run that up and you’ll have staf ready to go.
> 
> docker pull broderickhigby/openpose-staf:latest
> 
> Medium article to set it up:
> https://medium.com/@brodyhigby/how-to-get-openpose-with-spatial-temporal-fields-running-in-under-5-minutes-123e94aafe12
> 
> Wrote this on my phone.

@BroderickHigby: Thank you so much for your response,
I am already following your Github repo and docker images, I build the container successfully but while I run the command for server, I got the error messages:

root@dd03d47cc00d:/openpose# ./build/examples/openpose/openpose.bin --video examples/media/video.avi --write_video /atif/nol22.avi --write_json /atif/poses/   --model_pose BODY_25 --render_pose 2 --tracking 0 --number_people_max 1 --display 0
Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.

Error:
Prototxt file not found: models/pose/body_21a/pose_deploy.prototxt.
Possible causes:
        1. Not downloading the OpenPose trained models.
        2. Not running OpenPose from the same directory where the `model` folder is located.
        3. Using paths with spaces.

Coming from:
- /openpose/src/openpose/net/netCaffe.cpp:ImplNetCaffe():58
- /openpose/src/openpose/net/netCaffe.cpp:ImplNetCaffe():94
- /openpose/src/openpose/pose/poseExtractorCaffe.cpp:addCaffeNetOnThread():108
- /openpose/src/openpose/pose/poseExtractorCaffe.cpp:netInitializationOnThread():198
- /openpose/src/openpose/pose/poseExtractorNet.cpp:initializationOnThread():98
- /openpose/src/openpose/pose/poseExtractor.cpp:initializationOnThread():34
- /openpose/include/openpose/pose/wPoseExtractor.hpp:initializationOnThread():57
- /openpose/include/openpose/thread/worker.hpp:initializationOnThreadNoException():77

Error occurred on a thread. OpenPose closed all its threads and then propagated the error to the main thread. Error description:

Prototxt file not found: models/pose/body_21a/pose_deploy.prototxt.
Possible causes:
        1. Not downloading the OpenPose trained models.
        2. Not running OpenPose from the same directory where the `model` folder is located.
        3. Using paths with spaces.

Coming from:
- /openpose/src/openpose/net/netCaffe.cpp:ImplNetCaffe():58
- /openpose/src/openpose/net/netCaffe.cpp:ImplNetCaffe():94
- /openpose/src/openpose/pose/poseExtractorCaffe.cpp:addCaffeNetOnThread():108
- /openpose/src/openpose/pose/poseExtractorCaffe.cpp:netInitializationOnThread():198
- /openpose/src/openpose/pose/poseExtractorNet.cpp:initializationOnThread():98
- /openpose/src/openpose/pose/poseExtractor.cpp:initializationOnThread():34
- /openpose/include/openpose/pose/wPoseExtractor.hpp:initializationOnThread():57
- /openpose/include/openpose/thread/worker.hpp:initializationOnThreadNoException():77
- [All threads closed and control returned to main thread]
- /openpose/src/openpose/utilities/errorAndLog.cpp:checkWorkerErrors():280
- /openpose/include/openpose/thread/threadManager.hpp:stop():243
- /openpose/include/openpose/thread/threadManager.hpp:exec():202
- /openpose/include/openpose/wrapper/wrapper.hpp:exec():444
root@dd03d47cc00d:/openpose#


in your docker images, while I opened the model's folder, it has  body_21a  body_21a_video  body_25  coco mpi model. The model body_21a_video  has "pose_deploy.prototxt." this file but model body_21a  only has this file "pose_iter_XXXXXX.caffemodel".

Please help me with this issue. Thanks

**Comment by AtifSarwar29** [comment]
> Hey @AtifSarwar29, this was a huge pain for me. If you go into the pose_tracking file and change body_25 to body_21 that should fix it. Also, make sure that the body_21 model is actually downloaded in your models/pose folder. Then rebuild the project using:
> cd build/; make -j `nproc`; cd ../
> 
> Check out my branch if you need to:
> https://github.com/BroderickHigby/openpose/tree/staf-ubuntu
> 
> Last ditch efforts, if you want, here’s my docker. You just run that up and you’ll have staf ready to go.
> 
> docker pull broderickhigby/openpose-staf:latest
> 
> Medium article to set it up:
> https://medium.com/@brodyhigby/how-to-get-openpose-with-spatial-temporal-fields-running-in-under-5-minutes-123e94aafe12
> 
> Wrote this on my phone.

@BroderickHigby I also followed your GitLab repo and used all the command which you mentioned but when I used "make command". this command is not working and gave me this error. 

-- Build files have been written to: /openpose/build
[  3%] Built target openpose_lib
[  4%] Building CXX object src/openpose/CMakeFiles/openpose.dir/pose/poseParameters.cpp.o
[  5%] Building CXX object src/openpose/CMakeFiles/openpose.dir/pose/poseRenderer.cpp.o
[  5%] Building CXX object src/openpose/CMakeFiles/openpose.dir/pose/poseTracker.cpp.o
[  5%] Building CXX object src/openpose/CMakeFiles/openpose.dir/pose/renderPose.cpp.o
[  5%] Building CXX object src/openpose/CMakeFiles/openpose.dir/producer/flirReader.cpp.o
[  5%] Building CXX object src/openpose/CMakeFiles/openpose.dir/producer/defineTemplates.cpp.o
[  6%] Building CXX object src/openpose/CMakeFiles/openpose.dir/producer/spinnakerWrapper.cpp.o
[  6%] Building CXX object src/openpose/CMakeFiles/openpose.dir/producer/ipCameraReader.cpp.o
[  7%] Building CXX object src/openpose/CMakeFiles/openpose.dir/producer/imageDirectoryReader.cpp.o
[  7%] Building CXX object src/openpose/CMakeFiles/openpose.dir/producer/videoReader.cpp.o
[  7%] Building CXX object src/openpose/CMakeFiles/openpose.dir/producer/videoCaptureReader.cpp.o
[  7%] Building CXX object src/openpose/CMakeFiles/openpose.dir/producer/producer.cpp.o
/openpose/src/openpose/pose/poseParameters.cpp:425:5: error: too many initializers for 'const std::array<std::__cxx11::basic_string<char>, 16>'
     };
     ^
compilation terminated due to -Wfatal-errors.
src/openpose/CMakeFiles/openpose.dir/build.make:5244: recipe for target 'src/openpose/CMakeFiles/openpose.dir/pose/poseParameters.cpp.o' failed
make[2]: *** [src/openpose/CMakeFiles/openpose.dir/pose/poseParameters.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /openpose/src/openpose/pose/poseTracker.cpp:6:0:
/openpose/include/openpose/pose/poseTracker.hpp: In member function 'void op::PoseTracker::computeVelocity(op::Tracklet&)':
/openpose/include/openpose/pose/poseTracker.hpp:130:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 for(int j=1; j<tracklet.kp_queue.size(); j++){
                              ~^~~~~~~~~~~~~~~~~~~~~~~~~
/openpose/src/openpose/pose/poseTracker.cpp: In function 'std::pair<int, int> op::mostCommon(std::vector<int>&, int)':
/openpose/src/openpose/pose/poseTracker.cpp:34:72: warning: unused parameter 'exclude' [-Wunused-parameter]
     std::pair<int, int> mostCommon(std::vector<int>& lst, int exclude=-1){
                                                                        ^
/openpose/src/openpose/pose/poseTracker.cpp: In member function 'std::vector<int> op::PoseTracker::computeTrackScore(op::Array<float>&, int, std::pair<op::Array<float>, std::map<int, int> >&)':
/openpose/src/openpose/pose/poseTracker.cpp:90:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for(int i=0; i<mTafPartPairs.size()/2; i++){
                      ~^~~~~~~~~~~~~~~~~~~~~~~
CMakeFiles/Makefile2:785: recipe for target 'src/openpose/CMakeFiles/openpose.dir/all' failed
make[1]: *** [src/openpose/CMakeFiles/openpose.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2


for  reference, I have mentioned all the command below which used before the make command:

# Launch instance, then pull Docker
docker pull cwaffles/openpose
# get inside container
docker run -it --rm --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=0 cwaffles/openpose

# update openpose on docker container
git fetch origin
git pull
# Add remote repo
git remote add brody-op https://github.com/BroderickHigby/openpose.git
git fetch brody-op
git checkout --track brody-op/staf

the command which gave me error right now:
# Build C code
cd build/; make -j `nproc`; cd ../

**Comment by soulslicer** [comment]
I'm not sure whats going on here. Only Body 21 is supported, and you need to checkout the staf branch

**Comment by ChongMingWei** [comment]
@soulslicer 
Yes, I use the staf branch openpose. 
Successfully make the project and execute it.

**Comment by ChongMingWei** [comment]
If somebody faced the condition that the body_21a model cannot be found, please check the repository you download is under the brach **staf**.
> git clone https://github.com/soulslicer/openpose.git -b staf
