### ISSUE TITLE
BODY_21A does not correspond to any model error

### ISSUE THREAD

**Issue by Naveennavik** [soulslicer/openpose#7]
Hi @soulslicer, i am able to build openpose on ubuntu machine without any errors but when i run the command:
build/examples/openpose/openpose.bin --model_pose BODY_21A --tracking 1 --render_pose 1
i get the error 
String ('BODY_21A') does not correspond to any model (BODY_25, COCO, MPI, MPI_4_layers)
where as it is able to work for BODY_25 model with tracking 0. Can you pls help what is going wrong?
Thanks in advance.

**Comment by mkocabas** [comment]
Did you checkout the `staf` branch before compiling?

**Comment by maartenjv** [comment]
I had a similar issue. Noticed that the getModels.bat script does not download the body21a, but the getModels.sh does.
